name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Verify formatting
        run: make fmt-check
      - name: Lint
        run: make lint
      - name: Test
        run: make test

